### ISSUE TITLE
Update dependencies on inAppBrowser

### ISSUE THREAD

**Issue by phvannor** [Azure/azure-mobile-services-cordova#1]
It appears that 0.5.2 doesn't work with mobile services (https://social.msdn.microsoft.com/Forums/azure/en-US/fac938b9-0c34-4f72-80a0-45d368e78904/azure-mobile-service-phonegap-app-google-login-error?forum=azuremobile)

We should update the xml to specify a minimum version that will work (0.5.4?)

**Comment by danderson00** [comment]
plugin.xml does not yet support versioning - see https://cordova.apache.org/docs/en/5.0.0/plugin_ref_spec.md.html#Plugin%20Specification_dependency_element.

Versioning is likely one of the reasons plugins were moved to npm - we'll keep an eye on things and introduce version constraints when they are implemented.

**Comment by sgrebnov** [comment]
Should `org.apache.cordova.inappbrowser` be changed to `cordova-plugin-inappbrowser` ?
https://github.com/Azure/azure-mobile-services-cordova/blob/master/plugin.xml#L16
