### ISSUE TITLE
Is this don't work with Mobile App?

### ISSUE THREAD

**Issue by alexsandro-xpt** [Azure/azure-mobile-services-cordova#13]
I'm looking for cordova integraton but I only found for Mobile Services at https://azure.microsoft.com/pt-br/documentation/articles/mobile-services-javascript-backend-phonegap-get-started/

In Mobile App I can't see anything about Cordova
https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-android-get-started/

**Comment by adrianhall** [comment]
We are working on Azure Mobile Apps Cordova Plugin.  We expect a preview release soon (within the next few weeks) that will cover authentication and data access.  Offline sync and push support will be some time out.  Look for beta releases to the npm repository.

**Comment by alexsandro-xpt** [comment]
I'm looking for push notification feature.

Thanks!
