### ISSUE TITLE
Error 404 on update

### ISSUE THREAD

**Issue by juanredondo** [Azure/azure-mobile-services-cordova#21]
Can't update from Visual Studio to the last version of the plugin. The output message :

> CordovaError: Failed to fetch plugin com.microsoft.azure-mobile-services via registry.
> Probably this is either a connection problem, or plugin spec is incorrect.
> Check your connection and plugin name/version/URL.
> Error: Registry returned 404 for GET on https://registry.npmjs.org/com.microsoft.azure-mobile-services
>     at C:\Users\jredondo\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\fetch.js:146:33
>     at _rejected (C:\Users\jredondo\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:797:24)
>     at C:\Users\jredondo\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:823:30
>     at Promise.when (C:\Users\jredondo\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:1035:31)
>     at Promise.promise.promiseDispatch (C:\Users\jredondo\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:741:41)
>     at C:\Users\jredondo\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:557:44
>     at flush (C:\Users\jredondo\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:108:17)
>     at process._tickCallback (node.js:355:11)
> Lis.

**Comment by shrishrirang** [comment]
@juanredondo The recently released Cordova plugin is for Azure Mobile Apps. If that is what you are looking for this is what you need to install: https://www.npmjs.com/package/cordova-plugin-ms-azure-mobile-apps. Let me know if you have any trouble using it.

**Comment by shrishrirang** [comment]
.. and feel free to reactivate if that doesn't address your issue!

**Comment by RJEspera** [comment]
I had a problem getting the plugin to work.  I've downloaded it using npm, and added the plugin as custom local that gave me error saying something a folder location not recognized.

I did, however, was able to load the plugin using the files from ‘Quickstart’ generated project from Azure Mobile Apps.

I've compared the files, plugin.xml, etc.  and they look identical same beta3 version as well.  I'm not sure while the nom extracted file will not load.

BTW, I'm using 2015 with Cordova and Ionic framework. 

Sent from Windows Mail

From: Shrirang Shirodkar
Sent: ‎Tuesday‎, ‎February‎ ‎16‎, ‎2016 ‎3‎:‎17‎ ‎PM
To: Azure/azure-mobile-services-cordova

@juanredondo The recently released Cordova plugin is for Azure Mobile Apps. If that is what you are looking for this is what you need to install: https://www.npmjs.com/package/cordova-plugin-ms-azure-mobile-apps. Let me know if you have any trouble using it.

**Comment by shrishrirang** [comment]
@RJEspera Can you try using:

```
 cordova plugin add cordova-plugin-ms-azure-mobile-apps
```

Downloading using npm and then installing from that path should work too. May be you'd want to double check your Cordova CLI version.
