### ISSUE TITLE
How to clear cache data

### ISSUE THREAD

**Issue by mrvamsidhar** [Azure/azure-mobile-services-cordova#25]
Once user authenticated if he is not authorized then I should restrict him to proceed further. I am able to restrict him for further proceeding. but when I try to login as different user, Outh window has previous credentials and it is trying to log in as previous user. I need to delete oauth cache in phonegap application. any idea?

**Comment by adrianhall** [comment]
There is no "oauth cache".  The pop-up window is a web view and web views can store cookies.  You need to delete the cookies associated with the oauth provider.  For example, if you are authenticating with twitter, then deleting the cookies associates with *.twitter.com will likely remove the effect you are seeing.   note that the cookiejar is across the browser - so Safari on Apple, Chrome on Android, etc.
