### ISSUE TITLE
Dependencies on inAppBrowser

### ISSUE THREAD

**Issue by usmakas** [Azure/azure-mobile-services-cordova#27]
I update phonegap version 3.70 to cli-5.2.0 but I can't build in androip app
I use this plugin for push notificiton service.

It display eror message follow below,
Error - Some official plugins have to be updated if using PhoneGap >= 4.0.0. Please upgrade the version of any plugins that may include the following file: InAppBrowser.java

Installing "org.apache.cordova.statusbar" at "0.1.4" for android
Installing "com.phonegap.plugins.facebookconnect" at "0.9.0" for android
Installing "com.adobe.plugins.GAPlugin" at "2.4.0" for android
Installing "org.apache.cordova.inappbrowser" at "0.5.2" for android
**Installing "com.microsoft.azure-mobile-services" at "1.2.8" for android
Notice: org.apache.cordova.inappbrowser has been automatically converted to cordova-plugin-inappbrowser and fetched from npm. This is due to our old plugins registry shutting down.
cordova-plugin-inappbrowser" will not install due to "/project/cordova/plugins/org.apache.cordova.inappbrowser" being installed.
Dependent plugin "org.apache.cordova.inappbrowser" already installed on android.**
Installing "com.phonegap.plugins.PushPlugin" at "2.5.0" for android
Installing "ptdev.makingwaves2.estimotes" at "1.0.1" for android
Installing "org.apache.cordova.vibration" at "0.3.13" for android
Installing "org.apache.cordova.dialogs" at "0.3.0" for android
Installing "org.apache.cordova.camera" at "0.3.6" for android
Installing "org.apache.cordova.network-information" at "0.2.15" for android
Installing "org.apache.cordova.geolocation" at "0.3.12" for android
Installing "org.apache.cordova.device" at "0.3.0" for android
Fetching plugin "cordova-plugin-whitelist" via npm
Installing "cordova-plugin-whitelist" at "1.2.2" for android

```
           This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.
```

Fetching plugin "cordova-plugin-inappbrowser" via npm
cordova-plugin-inappbrowser" will not install due to "/project/cordova/plugins/org.apache.cordova.inappbrowser" being installed.
Plugin "org.apache.cordova.inappbrowser" already installed on android.

**Comment by adrianhall** [comment]
This is a problem with your upgrade.  The problem is that things changed too much between the two versions.  You probably have to uninstall all the plugins, clean your project and then re-install the plugins again.
