### ISSUE TITLE
logout doesn't completly logs out

### ISSUE THREAD

**Issue by bjoernboeckle** [Azure/azure-mobile-services-cordova#29]
I'm having the scenario that I want to authenticate users using microsoft or google accounts.
Everything works pretty well and as soon as I'm logout I cannot access the authorized controllers anymore (as expected).

But as soon as I'm calling login again the login is performed automatically (it’s not required to enter the user credentials again). This is fine and convenient as long as I want to login the same user again. But in my application I want to change the user; which is not possible at the moment since the previous user is just automatically logged in so the new user never has the chance to login. 
From a security point of view this is even worse because this means that not authenticated users can just use the old login of the previous user to access the other users data (even when the user previously successfully logged out).

So the flow must be:
1. client.login(...
2. // User does authenticated actions
3. client.logout();
// A new user is required this time!!! Which is not possible since the login happens automatically!
4. client.login(...   

This question was also already asked in Stackoverflow by a different user:
http://stackoverflow.com/questions/32928370/how-do-you-completely-log-out-of-azure-with-google-provider

**Comment by adrianhall** [comment]
The short version is you don't.  This is a restriction of the fact that Google really really doesn't want you to log out of their web interface, so you have to go to the web interface of Google to sign out.

Really, the only possible way.  To login:
1) Use the Google Client SDK or OAuth2 interface to log the user in without using a web view.  
2) Call the client.login("google", { access_token: <your-google-token> });

To logout:
3) When you log out, do a GET of https://yoursite.azurewebsites.net/.auth/logout to remove the token from ZUMO
4) Do the google Client SDK log out process or Google OAuth logout process.

**Comment by bjoernboeckle** [comment]
Ok thank you very much for the very fast answer, so a quick solution for me could be to just not support google accounts.
But it's the same behaviour with Microsoft accounts?

**Comment by adrianhall** [comment]
Yes - it is pretty much the same with all web-based social providers (i.e. anything but AAD) - the logout is not really a log out unless you go to the web site and log out of the provider, which will log out of all web sites that use that provider in one fell swoop.
