### ISSUE TITLE
404 on getTable

### ISSUE THREAD

**Issue by mattheuspirovani** [Azure/azure-mobile-services-cordova#31]
Created a Mobile App Quick Start
Downloaded the Cordova Sample
Added the android platform
Everything works fine until then, buuuut running this line:

todoItemTable = client.getTable('todoitem');

Throws the following error

Failed to load resource: the server responded with a status of 404 (Not Found) https://xxxxxmobapp.azurewebsites.net/tables/todoitem?$filter=(complete%20eq%20false)
Not Found - 404

**Comment by adrianhall** [comment]
This repository is for the azure mobile services - it is no longer in active development and you should not be using this.

That being said, you should check to see if your backend has a todoitem table - this can be checked in Easy Tables in the Azure portal if you have used the Quickstart
