### ISSUE TITLE
Unable to find API reference

### ISSUE THREAD

**Issue by wolfen351** [Azure/azure-mobile-services-cordova#32]
Hi there

Please indicate in the readme or somewhere else in this repo, where to find the API reference?

Thanks!

**Comment by shrishrirang** [comment]
Azure Mobile Services has been deprecated and is now superseded by Azure Mobile Apps.

For connecting to Azure Mobile Apps refer https://github.com/Azure/azure-mobile-apps-cordova-client. You can find the API reference for the JS / Cordova SDK for Azure Mobile Apps at http://azure.github.io/azure-mobile-apps-js-client.

**Comment by wolfen351** [comment]
Thanks, but most important for me is that this is on the "front page" readme.md file, please can you add this important info there?

**Comment by shrishrirang** [comment]
I updated the Readme earlier today. Thanks for bringing this up.
