### ISSUE TITLE
Register Notification Hub for Windows Notification Service

### ISSUE THREAD

**Issue by AlexFromGPec** [Azure/azure-mobile-services-cordova#7]
In my Cordova APP, I cannot use this plugin to register notification hub for Windows Notification Service, but it's ok for Android GCM  & iOS APNS. Does this plugin support push notifications for Cordova app on Windows 8.1 using WNS?

**Comment by danderson00** [comment]
The cordova plugin uses the web version of Mobile Services (as opposed to the WinJS version) which does not support WNS notifications at this time. The Mobile Apps Javascript client SDK will support WNS when it is released. You can vote for this feature on the UserVoice site (http://feedback.azure.com/forums/216254-mobile-apps-formerly-mobile-services).

**Comment by candidodmv** [comment]
@danderson00 What is your suggest to succeed with this implementation on windows 8.1 with Windows Notification Service (WNS) ?

**Comment by candidodmv** [comment]
@phvannor could you help us?

**Comment by phvannor** [comment]
Long term we'd like everyone to use the newer push APIs on the 2.0 JS SDK (https://github.com/Azure/azure-mobile-apps-js-client) but that is not yet GA and requires using a Mobile App backend.

In the meantime if you are using services, the proposed PR is what I've recommended anyone do that really needs WNS.  (That method doesn't work for secondary tiles, but that isn't a huge deal)   

I'm not opposed to taking the PR, but we do need to move the changes over to the -services repo so its in the raw source not just in this repo which is more a release vehicle.  We probably will not though add any test automation/etc on it, so it will be supported but untested from our point of view.
